### ISSUE TITLE
Add licensing information

### ISSUE THREAD

**Issue by akien-mga** [oxrock/Godot-camera-raycasting-demo#4]
Hi there,

It would be nice if you could add licensing information to the repo so that people know to which extent they can base their work on your demo. For a Godot demo I would advise the MIT license, so people can basically do whatever they want and it could even be integrated in the main Godot repo.

**Comment by oxrock** [comment]
Will do, the idea was to give back to the community so it's absolutely open to be used by anyone.

**Comment by oxrock** [comment]
License text was added, as the license states: Anyone can use the project for any of their project needs.

**Comment by akien-mga** [comment]
Thanks!
